# Generated by Django 4.2.17 on 2025-02-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAndLiterature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artandliterature',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
