# Generated by Django 4.2.17 on 2025-02-07 15:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAndLiterature', '0002_artandliterature_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artandliterature',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
