# Generated by Django 4.2.17 on 2025-02-07 16:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAndLiterature', '0003_alter_artandliterature_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artandliterature',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
