# Generated by Django 4.2.17 on 2025-02-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAndLiterature', '0004_alter_artandliterature_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='artandliterature',
            name='view',
            field=models.IntegerField(default=1),
        ),
    ]
