# Generated by Django 4.2.17 on 2025-02-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAndLiterature', '0005_artandliterature_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artandliterature',
            old_name='view',
            new_name='views',
        ),
    ]
