# Generated by Django 4.2.17 on 2025-02-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAndLiterature', '0006_rename_view_artandliterature_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artandliterature',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
