# Generated by Django 4.2.17 on 2025-02-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAndLiterature', '0007_alter_artandliterature_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='artandliterature',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtAndLiterature.contentstatus'),
        ),
    ]
