# Generated by Django 4.2.17 on 2025-02-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAndLiterature', '0008_contentstatus_artandliterature_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artandliterature',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtAndLiterature.contentstatus'),
        ),
    ]
