# Generated by Django 4.2.17 on 2025-02-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAndLiterature', '0009_alter_artandliterature_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
