# Generated by Django 4.2.17 on 2025-02-11 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_tag'),
        ('ArtAndLiterature', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artandliterature',
            name='tag',
            field=models.ManyToManyField(to='config.tag'),
        ),
        migrations.AlterField(
            model_name='artandliterature',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.contentstatus'),
        ),
        migrations.DeleteModel(
            name='ContentStatus',
        ),
    ]
