# Generated by Django 4.2.17 on 2025-02-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAndLiterature', '0012_artandliterature_tag_alter_artandliterature_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artandliterature',
            old_name='tag',
            new_name='tags',
        ),
    ]
