# Generated by Django 4.2.17 on 2025-02-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAndLiterature', '0013_rename_tag_artandliterature_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='artandliterature',
            name='m_comment',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
    ]
