# Generated by Django 4.2.17 on 2025-02-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_revisedcomment_revisedby'),
        ('ArtAndLiterature', '0014_artandliterature_m_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artandliterature',
            name='m_comment',
        ),
        migrations.AddField(
            model_name='artandliterature',
            name='revised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.revisedby'),
        ),
        migrations.AddField(
            model_name='artandliterature',
            name='revised_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.revisedcomment'),
        ),
    ]
