# Generated by Django 4.2.17 on 2025-02-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_revisedcomment_revisedby'),
        ('ArtAndLiterature', '0015_remove_artandliterature_m_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artandliterature',
            name='status',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.contentstatus'),
        ),
        migrations.AlterField(
            model_name='artandliterature',
            name='tags',
            field=models.ManyToManyField(blank=True, to='config.tag'),
        ),
    ]
