# Generated by Django 4.2.17 on 2025-02-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAndLiterature', '0016_alter_artandliterature_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artandliterature',
            old_name='revised_by',
            new_name='reviewed_by',
        ),
        migrations.RenameField(
            model_name='artandliterature',
            old_name='revised_comments',
            new_name='reviewed_comments',
        ),
    ]
