# Generated by Django 4.2.17 on 2025-02-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_user_is_editior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_editior',
            new_name='is_editor',
        ),
    ]
