# Generated by Django 5.1.3 on 2025-01-06 11:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalInsight', '0002_alter_medicalscience_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalscience',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
